#!/bin/sh

# Set these paths appropriately

BIN="/Users/wolfi/Documents/Uni/Computerlinguistik/CL_time_expression_recognition/TemporalExpressionsCheck/dependencies/newpyheideltimetest/bin"
CMD="/Users/wolfi/Documents/Uni/Computerlinguistik/CL_time_expression_recognition/TemporalExpressionsCheck/dependencies/newpyheideltimetest/cmd"
LIB="/Users/wolfi/Documents/Uni/Computerlinguistik/CL_time_expression_recognition/TemporalExpressionsCheck/dependencies/newpyheideltimetest/lib"

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/german-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german-spoken.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE
