#!/bin/sh

# Set these paths appropriately

BIN="/Users/wolfi/Documents/Uni/Computerlinguistik/CL_time_expression_recognition/TemporalExpressionsCheck/dependencies/newpyheideltimetest/bin"
CMD="/Users/wolfi/Documents/Uni/Computerlinguistik/CL_time_expression_recognition/TemporalExpressionsCheck/dependencies/newpyheideltimetest/cmd"
LIB="/Users/wolfi/Documents/Uni/Computerlinguistik/CL_time_expression_recognition/TemporalExpressionsCheck/dependencies/newpyheideltimetest/lib"

TOKENIZER=${BIN}/separate-punctuation
SPLITTER=${CMD}/portuguese-splitter.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/portuguese-abbreviations
POST_TAGGING=${CMD}/portuguese-post-tagging
PARFILE=${LIB}/portuguese-finegrained.par

# splitting 
$SPLITTER $* |
# pre-tokenization
sed "s/\([\)\"\'\?\!]\)\([\.\,\;\:]\)/ \1 \2/g" |
# tokenizing
$TOKENIZER +1 +s +l $ABBR_LIST |
# remove empty lines
grep -v '^$' |
# tagging
$TAGGER $PARFILE -token -lemma -sgml | 
$POST_TAGGING -yes
