#!/bin/sh

# Set these paths appropriately

BIN="/Users/wolfi/Documents/Uni/Computerlinguistik/CL_time_expression_recognition/TemporalExpressionsCheck/dependencies/newpyheideltimetest/bin"
CMD="/Users/wolfi/Documents/Uni/Computerlinguistik/CL_time_expression_recognition/TemporalExpressionsCheck/dependencies/newpyheideltimetest/cmd"
LIB="/Users/wolfi/Documents/Uni/Computerlinguistik/CL_time_expression_recognition/TemporalExpressionsCheck/dependencies/newpyheideltimetest/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
TAGGER=tree-tagger
ABBR_LIST=${LIB}/portuguese-abbreviations
PARFILE=${LIB}/portuguese2.par

$TOKENIZER -p -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
