#!/bin/sh

# Set these paths appropriately

BIN="/Users/wolfi/Documents/Uni/Computerlinguistik/CL_time_expression_recognition/TemporalExpressionsCheck/dependencies/newpyheideltimetest/bin"
CMD="/Users/wolfi/Documents/Uni/Computerlinguistik/CL_time_expression_recognition/TemporalExpressionsCheck/dependencies/newpyheideltimetest/cmd"
LIB="/Users/wolfi/Documents/Uni/Computerlinguistik/CL_time_expression_recognition/TemporalExpressionsCheck/dependencies/newpyheideltimetest/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
