monday :- N : (nth:<n,<s,s>> 1:n (intersect:<s,<s,s>> day:s week:s))
tuesday :- N : (nth:<n,<s,s>> 2:n (intersect:<s,<s,s>> day:s week:s))
wednesday :- N : (nth:<n,<s,s>> 3:n (intersect:<s,<s,s>> day:s week:s))
thursday :- N : (nth:<n,<s,s>> 4:n (intersect:<s,<s,s>> day:s week:s))
friday :- N : (nth:<n,<s,s>> 5:n (intersect:<s,<s,s>> day:s week:s))
saturday :- N : (nth:<n,<s,s>> 6:n (intersect:<s,<s,s>> day:s week:s))
sunday :- N : (nth:<n,<s,s>> 7:n (intersect:<s,<s,s>> day:s week:s))
